"""Readiness memo assembly — deterministic body, optional AI narrative."""

from collections import defaultdict
from datetime import date


def build_fallback_narrative(readiness_score, gaps, safe_harbour_results):
    """Deterministic narrative used when Claude is unavailable or declined."""
    high = [g for g in gaps if g["severity"] == "high"]
    blocked_jurisdictions = sorted({g["jurisdiction"] for g in high})
    requests = defaultdict(set)
    for g in gaps:
        requests[g["likely_owner"]].add(g["suggested_action"])
    cannot = [r["jurisdiction"] for r in safe_harbour_results if r["can_evaluate"] != "Yes"]
    return {
        "executive_summary": (
            f"[DETERMINISTIC DRAFT] Overall data readiness is {readiness_score:.0%}. "
            f"{len(gaps)} data gaps were identified ({len(high)} high severity). "
            f"High-severity gaps currently block GloBE calculations in: "
            f"{', '.join(blocked_jurisdictions) if blocked_jurisdictions else 'none'}."
        ),
        "key_blockers": [
            f"{g['jurisdiction']} / {g['entity']}: {g['field_label']} — blocks {g['blocks']}" for g in high
        ],
        "priority_jurisdictions": blocked_jurisdictions or ["None — no high-severity gaps"],
        "data_requests": [
            {"owner": owner, "request": "; ".join(sorted(items))} for owner, items in sorted(requests.items())
        ],
        "open_questions_for_tax_review": [
            f"Safe harbour evaluation incomplete for: {', '.join(cannot)}" if cannot
            else "All jurisdictions evaluable for transitional safe harbour tests.",
            "Confirm local GAAP vs group reporting basis for PBT before relying on indicative results.",
        ],
    }


def memo_to_markdown(narrative, readiness_score, gaps, gap_summary, safe_harbour_results,
                     mappings, group_alias, fiscal_year, narrative_source):
    """Render the full workpaper-style memo as Markdown."""
    lines = [
        f"# Pillar Two Data Readiness Memo — {group_alias}",
        "",
        f"*Fiscal year: FY{fiscal_year} • Prepared: {date.today().isoformat()} • "
        f"Narrative source: {narrative_source}*",
        "",
        "> **Demo disclaimer:** generated by a prototype for illustration only. Not tax advice. "
        "Does not implement the full OECD GloBE rules. All findings require tax professional review.",
        "",
        "## 1. Executive summary",
        "",
        narrative["executive_summary"],
        "",
        f"**Overall readiness score:** {readiness_score:.0%} (severity-weighted field completeness)",
        "",
        "## 2. Key blockers",
        "",
    ]
    lines += [f"- {b}" for b in narrative["key_blockers"]] or ["- None identified"]
    lines += ["", "## 3. Gaps by jurisdiction", "", "| Jurisdiction | High | Medium | Low | Total |",
              "| --- | ---: | ---: | ---: | ---: |"]
    for row in gap_summary:
        lines.append(f"| {row['jurisdiction']} | {row['high']} | {row['medium']} | {row['low']} | {row['total']} |")
    lines += ["", "## 4. Safe harbour readiness", "",
              "| Jurisdiction | Can evaluate? | Indicative passes | Missing items |",
              "| --- | --- | --- | --- |"]
    for r in safe_harbour_results:
        lines.append(
            f"| {r['jurisdiction']} | {r['can_evaluate']} | "
            f"{', '.join(r['indicative_passes']) or '—'} | {', '.join(r['missing_items']) or '—'} |"
        )
    lines += ["", "## 5. Missing data requests", ""]
    for req in narrative["data_requests"]:
        lines.append(f"- **{req['owner']}**: {req['request']}")
    lines += ["", "## 6. Priority jurisdictions for review", ""]
    lines += [f"- {j}" for j in narrative["priority_jurisdictions"]]
    lines += ["", "## 7. Open questions for tax technical review", ""]
    lines += [f"- {q}" for q in narrative["open_questions_for_tax_review"]]
    lines += ["", "## Appendix A — Detailed gap register", "",
              "| Jurisdiction | Entity | Missing field | Severity | Blocks | Likely owner |",
              "| --- | --- | --- | --- | --- | --- |"]
    for g in gaps:
        lines.append(
            f"| {g['jurisdiction']} | {g['entity']} | {g['field_label']} | {g['severity']} | "
            f"{g['blocks']} | {g['likely_owner']} |"
        )
    lines += ["", "## Appendix B — Approved source-to-field mappings", "",
              "| Source file | Sheet | Column | Mapped field | Confidence | Approved |",
              "| --- | --- | --- | --- | ---: | --- |"]
    for m in mappings:
        lines.append(
            f"| {m['source_file']} | {m['source_sheet']} | {m['source_column']} | "
            f"{m['field_label']} | {m['confidence']:.2f} | {'yes' if m['approved'] else 'no'} |"
        )
    lines.append("")
    return "\n".join(lines)
